export const SITE_CONFIG = {
  name: "Chantier Pro",
  email: "chantierprobj@gmail.com",
  supportEmail: (process.env.NEXT_PUBLIC_SUPPORT_EMAIL || "chantierprobj@gmail.com").trim(),
  logoPath: "/logo.png",
  whatsappDisplay: "+229 01 58 68 45 48",
  whatsappRaw: "2290158684548",
  whatsappUrl: "https://wa.me/2290158684548",
  instagramHandle: "@chantierprobj",
  instagramUrl: "https://www.instagram.com/chantierprobj",
  tiktokHandle: "@chantier.pro.app",
  tiktokUrl: "https://www.tiktok.com/@chantier.pro.app?_r=1&_t=ZN-96KVDaOpPIk",
  editor: "TCHONAN Rodolphe Karl",
  city: "Cotonou",
  country: "Bénin",
};
