import type { FeatureKey, UserPlan } from "@/lib/subscription/access";

export type CalculatorCategory =
  | "Béton"
  | "Acier / Ferraillage"
  | "Maçonnerie"
  | "Finitions"
  | "Toiture"
  | "Fondations"
  | "Dalles / Planchers"
  | "Escaliers"
  | "Coffrage"
  | "Terrassement"
  | "Laboratoire / Contrôle qualité"
  | "Documents / Rapports"
  | "Outils Entreprise";

export type CalculatorStatus = "AVAILABLE" | "SOON";

export type CalculatorCatalogItem = {
  id: string;
  title: string;
  description: string;
  category: CalculatorCategory;
  plan: UserPlan;
  href: string;
  featureKey?: FeatureKey;
  status: CalculatorStatus;
  iconName: string;
  isAvailable: boolean;
};

export const CALCULATORS_CATALOG: CalculatorCatalogItem[] = [
  {
    id: "concrete_basic",
    title: "Calcul béton (simple)",
    description: "Volume, dosage et estimation matériaux.",
    category: "Béton",
    plan: "FREE",
    href: "/dashboard/calculators/concrete",
    featureKey: "concrete_basic",
    status: "AVAILABLE",
    iconName: "🧱",
    isAvailable: true,
  },
  {
    id: "concrete_trucks",
    title: "Nombre de toupies béton",
    description: "Volume, capacité toupie, perte et recommandation.",
    category: "Béton",
    plan: "PREMIUM",
    href: "/dashboard/calculators/concrete-trucks",
    featureKey: "concrete_trucks",
    status: "AVAILABLE",
    iconName: "🚚",
    isAvailable: true,
  },
  {
    id: "steel_basic",
    title: "Calcul acier (simple)",
    description: "Longueurs, poids, barres 12m et coût estimatif.",
    category: "Acier / Ferraillage",
    plan: "FREE",
    href: "/dashboard/calculators/steel",
    featureKey: "steel_basic",
    status: "AVAILABLE",
    iconName: "🔩",
    isAvailable: true,
  },
  {
    id: "steel_weight",
    title: "Poids acier",
    description: "Poids total selon diamètre et longueur.",
    category: "Acier / Ferraillage",
    plan: "FREE",
    href: "/dashboard/calculators/steel-weight",
    status: "AVAILABLE",
    iconName: "⚖️",
    isAvailable: true,
  },
  {
    id: "rebar_columns",
    title: "Ferraillage poteaux",
    description: "Longitudinal, cadres, pertes et poids total (estimation).",
    category: "Acier / Ferraillage",
    plan: "PREMIUM",
    href: "/dashboard/calculators/rebar-columns",
    featureKey: "rebar_columns",
    status: "AVAILABLE",
    iconName: "🏛️",
    isAvailable: true,
  },
  {
    id: "rebar_beams",
    title: "Ferraillage poutres",
    description: "Aciers haut/bas, étriers, pertes et poids total (estimation).",
    category: "Acier / Ferraillage",
    plan: "PREMIUM",
    href: "/dashboard/calculators/rebar-beams",
    featureKey: "rebar_beams",
    status: "AVAILABLE",
    iconName: "🧰",
    isAvailable: true,
  },
  {
    id: "rebar_slab",
    title: "Ferraillage dalle (simple)",
    description: "Barres sens X/Y, recouvrements, pertes et poids (estimation).",
    category: "Acier / Ferraillage",
    plan: "PREMIUM",
    href: "/dashboard/calculators/rebar-slab",
    featureKey: "rebar_slab",
    status: "AVAILABLE",
    iconName: "🧱",
    isAvailable: true,
  },
  {
    id: "masonry_blocks",
    title: "Blocs / Agglos",
    description: "Surface de mur, nombre de blocs et marge de perte.",
    category: "Maçonnerie",
    plan: "FREE",
    href: "/dashboard/calculators/masonry-blocks",
    status: "AVAILABLE",
    iconName: "🧱",
    isAvailable: true,
  },
  {
    id: "paint_simple",
    title: "Peinture (simple)",
    description: "Surfaces, couches, rendement et estimation en litres.",
    category: "Finitions",
    plan: "FREE",
    href: "/dashboard/calculators/paint",
    status: "AVAILABLE",
    iconName: "🎨",
    isAvailable: true,
  },
  {
    id: "tiling_simple",
    title: "Carrelage (simple)",
    description: "Estimation carreaux, cartons et chutes.",
    category: "Finitions",
    plan: "FREE",
    href: "/dashboard/calculators/tiling",
    status: "AVAILABLE",
    iconName: "🧩",
    isAvailable: true,
  },
  {
    id: "quote_simple",
    title: "Devis (simple)",
    description: "Créer un devis simple depuis le dashboard.",
    category: "Documents / Rapports",
    plan: "FREE",
    href: "/dashboard/quotes",
    status: "AVAILABLE",
    iconName: "📄",
    isAvailable: true,
  },

  {
    id: "stair_straight",
    title: "Escalier droit",
    description: "Dimensions, confort et quantités béton/coffrage estimatives.",
    category: "Escaliers",
    plan: "PREMIUM",
    href: "/dashboard/calculators/stairs/straight",
    featureKey: "stair_straight",
    status: "AVAILABLE",
    iconName: "🪜",
    isAvailable: true,
  },
  {
    id: "masonry_advanced",
    title: "Maçonnerie (avancé)",
    description: "Blocs, mortier, surfaces et ouvertures.",
    category: "Maçonnerie",
    plan: "PREMIUM",
    href: "/dashboard/calculators/masonry",
    featureKey: "masonry",
    status: "AVAILABLE",
    iconName: "🧱",
    isAvailable: true,
  },
  {
    id: "paint_advanced",
    title: "Peinture (avancé)",
    description: "Supports, rendement, couches et variantes.",
    category: "Finitions",
    plan: "PREMIUM",
    href: "/dashboard/calculators/painting",
    featureKey: "painting",
    status: "AVAILABLE",
    iconName: "🎨",
    isAvailable: true,
  },
  {
    id: "plaster",
    title: "Enduit",
    description: "Quantités d’enduit, ciment/sable et surfaces.",
    category: "Finitions",
    plan: "PREMIUM",
    href: "/dashboard/calculators/plaster",
    featureKey: "plaster",
    status: "AVAILABLE",
    iconName: "🧱",
    isAvailable: true,
  },
  {
    id: "earthwork",
    title: "Terrassement",
    description: "Volumes de déblais/remblais estimatifs.",
    category: "Terrassement",
    plan: "PREMIUM",
    href: "/dashboard/calculators/earthwork",
    featureKey: "earthwork",
    status: "AVAILABLE",
    iconName: "🚜",
    isAvailable: true,
  },
  {
    id: "roofing",
    title: "Toiture",
    description: "Surfaces, pentes et quantités selon couverture.",
    category: "Toiture",
    plan: "PREMIUM",
    href: "/dashboard/calculators/roofing",
    featureKey: "roofing",
    status: "AVAILABLE",
    iconName: "🏠",
    isAvailable: true,
  },
  {
    id: "formwork",
    title: "Coffrage",
    description: "Surfaces de coffrage estimatives.",
    category: "Coffrage",
    plan: "PREMIUM",
    href: "/dashboard/calculators/formwork",
    featureKey: "formwork",
    status: "AVAILABLE",
    iconName: "🪵",
    isAvailable: true,
  },
  {
    id: "stair_landing",
    title: "Escalier avec palier",
    description: "Dimensions et quantités (MVP).",
    category: "Escaliers",
    plan: "PREMIUM",
    href: "/dashboard/calculators/stairs/landing",
    featureKey: "stair_landing",
    status: "AVAILABLE",
    iconName: "🪜",
    isAvailable: true,
  },

  {
    id: "stair_quarter_turn",
    title: "Escalier quart tournant",
    description: "Pré-dimensionnement et quantités (MVP).",
    category: "Escaliers",
    plan: "ENTERPRISE",
    href: "/dashboard/calculators/stairs/quarter-turn",
    featureKey: "stair_quarter_turn",
    status: "AVAILABLE",
    iconName: "🪜",
    isAvailable: true,
  },
  {
    id: "septic_tank",
    title: "Fosse septique / puisard",
    description: "Pré-dimensionnement et quantités (MVP).",
    category: "Outils Entreprise",
    plan: "ENTERPRISE",
    href: "/dashboard/calculators/septic-tank",
    featureKey: "septic_tank",
    status: "AVAILABLE",
    iconName: "🕳️",
    isAvailable: true,
  },
  {
    id: "fence",
    title: "Clôture",
    description: "Poteaux, linéaire et fondations (MVP).",
    category: "Outils Entreprise",
    plan: "ENTERPRISE",
    href: "/dashboard/calculators/fence",
    featureKey: "fence",
    status: "AVAILABLE",
    iconName: "🧱",
    isAvailable: true,
  },
  {
    id: "foundations",
    title: "Calculateurs Fondations",
    description: "Fouilles, propreté, béton, acier, coffrage, remblai et coût estimatif.",
    category: "Fondations",
    plan: "ENTERPRISE",
    href: "/dashboard/calculators/fondations",
    featureKey: "foundations",
    status: "AVAILABLE",
    iconName: "🏗️",
    isAvailable: true,
  },
  {
    id: "concrete_mix_design",
    title: "Formulation de béton",
    description: "Dosage indicatif : ciment, eau, sable, gravier, adjuvant et corrections d’humidité.",
    category: "Béton",
    plan: "ENTERPRISE",
    href: "/dashboard/calculators/formulation-beton",
    featureKey: "concrete_mix_design",
    status: "AVAILABLE",
    iconName: "🧪",
    isAvailable: true,
  },
  {
    id: "advanced_slab",
    title: "Dalle pleine (avancé)",
    description: "Béton, aciers, pertes et variantes.",
    category: "Dalles / Planchers",
    plan: "ENTERPRISE",
    href: "/dashboard/calculators/slab/advanced",
    featureKey: "advanced_slab",
    status: "AVAILABLE",
    iconName: "🧱",
    isAvailable: true,
  },

  {
    id: "slab_rc",
    title: "Dalle pleine BA",
    description: "Surface, béton, ferraillage X/Y et coût estimatif (estimation).",
    category: "Dalles / Planchers",
    plan: "PREMIUM",
    href: "/dashboard/calculators/slabs/reinforced",
    featureKey: "slab_rc",
    status: "AVAILABLE",
    iconName: "🧱",
    isAvailable: true,
  },
  {
    id: "slab_on_grade",
    title: "Dalle sur terre-plein",
    description: "Béton + couche de forme + sable + polyane/treillis (estimation).",
    category: "Dalles / Planchers",
    plan: "FREE",
    href: "/dashboard/calculators/slabs/on-grade",
    featureKey: "slab_on_grade",
    status: "AVAILABLE",
    iconName: "🪨",
    isAvailable: true,
  },
  {
    id: "slab_compression_hourdis",
    title: "Dalle de compression (hourdis)",
    description: "Béton compression, poutrelles, hourdis et treillis (estimation).",
    category: "Dalles / Planchers",
    plan: "PREMIUM",
    href: "/dashboard/calculators/slabs/compression-hourdis",
    featureKey: "slab_compression_hourdis",
    status: "AVAILABLE",
    iconName: "🏗️",
    isAvailable: true,
  },
  {
    id: "plancher_poutrelles_hourdis",
    title: "Plancher poutrelles-hourdis",
    description: "Surface, quantités de poutrelles/hourdis et béton de compression (estimation).",
    category: "Dalles / Planchers",
    plan: "PREMIUM",
    href: "/dashboard/calculators/slabs/poutrelles-hourdis",
    featureKey: "plancher_poutrelles_hourdis",
    status: "AVAILABLE",
    iconName: "🏗️",
    isAvailable: true,
  },

  {
    id: "lab_compressive_strength",
    title: "Résistance moyenne (compression)",
    description: "MPa, moyenne, min/max et écart entre éprouvettes.",
    category: "Laboratoire / Contrôle qualité",
    plan: "PREMIUM",
    href: "/dashboard/calculators/lab/compressive-strength",
    featureKey: "lab_compressive_strength",
    status: "AVAILABLE",
    iconName: "🧪",
    isAvailable: true,
  },
  {
    id: "lab_press_to_mpa",
    title: "Charge presse → MPa",
    description: "Conversion kN → MPa selon section de l’éprouvette.",
    category: "Laboratoire / Contrôle qualité",
    plan: "PREMIUM",
    href: "/dashboard/calculators/lab/press-to-mpa",
    featureKey: "lab_press_to_mpa",
    status: "AVAILABLE",
    iconName: "⚙️",
    isAvailable: true,
  },
  {
    id: "lab_fresh_density",
    title: "Masse volumique béton frais",
    description: "Calcul kg/m³ à partir de masse et volume du récipient.",
    category: "Laboratoire / Contrôle qualité",
    plan: "PREMIUM",
    href: "/dashboard/calculators/lab/fresh-density",
    featureKey: "lab_fresh_density",
    status: "AVAILABLE",
    iconName: "⚖️",
    isAvailable: true,
  },
  {
    id: "lab_slump_abram",
    title: "Affaissement cône d’Abrams",
    description: "Affaissement (mm) + interprétation indicative.",
    category: "Laboratoire / Contrôle qualité",
    plan: "PREMIUM",
    href: "/dashboard/calculators/lab/slump-abram",
    featureKey: "lab_slump_abram",
    status: "AVAILABLE",
    iconName: "📏",
    isAvailable: true,
  },

  {
    id: "enterprise_estimation",
    title: "Estimation complète d’un ouvrage",
    description: "Estimation globale (matériaux, main-d’œuvre, marge) + coût au m².",
    category: "Outils Entreprise",
    plan: "ENTERPRISE",
    href: "/dashboard/calculators/enterprise-estimation",
    featureKey: "enterprise_estimation",
    status: "AVAILABLE",
    iconName: "🏗️",
    isAvailable: true,
  },
  {
    id: "enterprise_quote_generator",
    title: "Générateur de devis automatique",
    description: "Devis simple avec lignes dynamiques, remise, marge et totaux.",
    category: "Outils Entreprise",
    plan: "ENTERPRISE",
    href: "/dashboard/calculators/enterprise-quote-generator",
    featureKey: "enterprise_quote_generator",
    status: "AVAILABLE",
    iconName: "🧾",
    isAvailable: true,
  },
  {
    id: "enterprise_smart_report",
    title: "Rapport chantier intelligent",
    description: "Génère un rapport structuré à partir des informations du jour.",
    category: "Outils Entreprise",
    plan: "ENTERPRISE",
    href: "/dashboard/calculators/enterprise-smart-report",
    featureKey: "enterprise_smart_report",
    status: "AVAILABLE",
    iconName: "🗒️",
    isAvailable: true,
  },
  {
    id: "enterprise_price_library",
    title: "Bibliothèque de prix",
    description: "Ajoute des prix unitaires, quantités optionnelles, et totalise tes lignes.",
    category: "Outils Entreprise",
    plan: "ENTERPRISE",
    href: "/dashboard/calculators/enterprise-price-library",
    featureKey: "enterprise_price_library",
    status: "AVAILABLE",
    iconName: "📚",
    isAvailable: true,
  },

  {
    id: "calc_history",
    title: "Historique des calculs",
    description: "MVP: historique global des calculs sauvegardés.",
    category: "Documents / Rapports",
    plan: "PREMIUM",
    href: "/dashboard/calculations/history",
    featureKey: "calc_history",
    status: "AVAILABLE",
    iconName: "🕘",
    isAvailable: true,
  },
  {
    id: "calc_pdf",
    title: "Export PDF calcul",
    description: "MVP: page imprimable + Enregistrer en PDF.",
    category: "Documents / Rapports",
    plan: "PREMIUM",
    href: "/dashboard/calculations/print",
    featureKey: "calc_pdf",
    status: "AVAILABLE",
    iconName: "📎",
    isAvailable: true,
  },
  {
    id: "quote_from_calc",
    title: "Créer un devis depuis un calcul",
    description: "MVP: pré-remplir un devis depuis un calcul.",
    category: "Documents / Rapports",
    plan: "PREMIUM",
    href: "/dashboard/quotes",
    featureKey: "quote_from_calc",
    status: "AVAILABLE",
    iconName: "🧾",
    isAvailable: true,
  },
  {
    id: "quote_templates",
    title: "Modèles rapides de devis",
    description: "MVP: modèles rapides de lignes de devis.",
    category: "Documents / Rapports",
    plan: "PREMIUM",
    href: "/dashboard/quotes",
    featureKey: "quote_templates",
    status: "AVAILABLE",
    iconName: "⚡",
    isAvailable: true,
  },

  {
    id: "dosage_library",
    title: "Bibliothèque de dosages",
    description: "Dosages indicatifs et repères terrain.",
    category: "Béton",
    plan: "PREMIUM",
    href: "/calculs/bibliotheque-dosages",
    featureKey: "dosage_library",
    status: "AVAILABLE",
    iconName: "📚",
    isAvailable: true,
  },
  {
    id: "project_budget",
    title: "Suivi budget chantier",
    description: "Budget initial, dépenses et alertes simples.",
    category: "Documents / Rapports",
    plan: "PREMIUM",
    href: "/calculs/budget-chantier",
    featureKey: "project_budget",
    status: "AVAILABLE",
    iconName: "💰",
    isAvailable: true,
  },
  {
    id: "daily_reports",
    title: "Rapports journaliers",
    description: "Journal de chantier (MVP) + export simple.",
    category: "Documents / Rapports",
    plan: "PREMIUM",
    href: "/calculs/rapports-journaliers",
    featureKey: "daily_reports",
    status: "AVAILABLE",
    iconName: "🗓️",
    isAvailable: true,
  },
  {
    id: "quote_mvp",
    title: "Devis (MVP)",
    description: "Créer un devis simple (saisie manuelle) + export.",
    category: "Documents / Rapports",
    plan: "PREMIUM",
    href: "/calculs/devis",
    featureKey: "quote_pdf",
    status: "AVAILABLE",
    iconName: "🧾",
    isAvailable: true,
  },

  {
    id: "price_library",
    title: "Bibliothèque prix matériaux",
    description: "Prix, unités et variantes par fournisseur.",
    category: "Outils Entreprise",
    plan: "ENTERPRISE",
    href: "/calculs/bibliotheque-prix",
    featureKey: "price_library",
    status: "AVAILABLE",
    iconName: "📚",
    isAvailable: true,
  },
  {
    id: "project_profitability",
    title: "Rentabilité chantier",
    description: "Marge, coûts et rentabilité par projet.",
    category: "Outils Entreprise",
    plan: "ENTERPRISE",
    href: "/calculs/rentabilite-chantier",
    featureKey: "project_profitability",
    status: "AVAILABLE",
    iconName: "📈",
    isAvailable: true,
  },
  {
    id: "reports_pdf",
    title: "Rapports chantier PDF",
    description: "Générer un rapport chantier en PDF (MVP).",
    category: "Documents / Rapports",
    plan: "ENTERPRISE",
    href: "/calculs/rapports-chantier-pdf",
    featureKey: "report_pdf",
    status: "AVAILABLE",
    iconName: "📄",
    isAvailable: true,
  },
  {
    id: "expenses_validation",
    title: "Validation dépenses",
    description: "Workflow simple de validation et contrôle.",
    category: "Outils Entreprise",
    plan: "ENTERPRISE",
    href: "/calculs/validation-depenses",
    featureKey: "expenses_validation",
    status: "AVAILABLE",
    iconName: "✅",
    isAvailable: true,
  },
  {
    id: "team_tracking",
    title: "Suivi équipe",
    description: "Affectations, présence et suivi (MVP).",
    category: "Outils Entreprise",
    plan: "ENTERPRISE",
    href: "/calculs/suivi-equipe",
    featureKey: "team_management",
    status: "AVAILABLE",
    iconName: "👷",
    isAvailable: true,
  },
  {
    id: "advanced_exports",
    title: "Exports avancés (Excel/PDF)",
    description: "Exports détaillés (PDF/CSV).",
    category: "Outils Entreprise",
    plan: "ENTERPRISE",
    href: "/calculs/exports-avances",
    featureKey: "advanced_exports",
    status: "AVAILABLE",
    iconName: "📤",
    isAvailable: true,
  },
];
