import type { FeatureKey, UserPlan } from "@/lib/subscription/access";

export type CalculatorCategory =
  | "Béton"
  | "Acier"
  | "Maçonnerie"
  | "Finition"
  | "Devis"
  | "Chantier"
  | "Outils Pro";

export type CalculatorStatus = "AVAILABLE" | "SOON";

export type CalculatorCatalogItem = {
  id: string;
  title: string;
  description: string;
  category: CalculatorCategory;
  plan: UserPlan;
  href: string;
  featureKey?: FeatureKey;
  status: CalculatorStatus;
  iconName: string;
  isAvailable: boolean;
};

export const CALCULATORS_CATALOG: CalculatorCatalogItem[] = [
  {
    id: "concrete_basic",
    title: "Calcul béton (simple)",
    description: "Volume, dosage et estimation matériaux.",
    category: "Béton",
    plan: "FREE",
    href: "/dashboard/calculators/concrete",
    featureKey: "concrete_basic",
    status: "AVAILABLE",
    iconName: "🧱",
    isAvailable: true,
  },
  {
    id: "steel_basic",
    title: "Calcul acier (simple)",
    description: "Longueurs, poids, barres 12m et coût estimatif.",
    category: "Acier",
    plan: "FREE",
    href: "/dashboard/calculators/steel",
    featureKey: "steel_basic",
    status: "AVAILABLE",
    iconName: "🔩",
    isAvailable: true,
  },
  {
    id: "steel_weight",
    title: "Poids acier",
    description: "Poids total selon diamètre et longueur.",
    category: "Acier",
    plan: "FREE",
    href: "/dashboard/calculators/steel-weight",
    status: "AVAILABLE",
    iconName: "⚖️",
    isAvailable: true,
  },
  {
    id: "masonry_blocks",
    title: "Blocs / Agglos",
    description: "Surface de mur, nombre de blocs et marge de perte.",
    category: "Maçonnerie",
    plan: "FREE",
    href: "/dashboard/calculators/masonry-blocks",
    status: "AVAILABLE",
    iconName: "🧱",
    isAvailable: true,
  },
  {
    id: "paint_simple",
    title: "Peinture (simple)",
    description: "Surfaces, couches, rendement et estimation en litres.",
    category: "Finition",
    plan: "FREE",
    href: "/dashboard/calculators/paint",
    status: "AVAILABLE",
    iconName: "🎨",
    isAvailable: true,
  },
  {
    id: "tiling_simple",
    title: "Carrelage (simple)",
    description: "Estimation carreaux, cartons et chutes.",
    category: "Finition",
    plan: "FREE",
    href: "/dashboard/calculators/tiling",
    status: "AVAILABLE",
    iconName: "🧩",
    isAvailable: true,
  },
  {
    id: "quote_simple",
    title: "Devis (simple)",
    description: "Créer un devis simple depuis le dashboard.",
    category: "Devis",
    plan: "FREE",
    href: "/dashboard/quotes",
    status: "AVAILABLE",
    iconName: "📄",
    isAvailable: true,
  },

  {
    id: "stair_straight",
    title: "Escalier droit",
    description: "Dimensions, confort et quantités béton/coffrage estimatives.",
    category: "Béton",
    plan: "PREMIUM",
    href: "/dashboard/calculators/stairs/straight",
    featureKey: "stair_straight",
    status: "AVAILABLE",
    iconName: "🪜",
    isAvailable: true,
  },
  {
    id: "masonry_advanced",
    title: "Maçonnerie (avancé)",
    description: "Blocs, mortier, surfaces et ouvertures.",
    category: "Maçonnerie",
    plan: "PREMIUM",
    href: "/dashboard/calculators/masonry",
    featureKey: "masonry",
    status: "AVAILABLE",
    iconName: "🧱",
    isAvailable: true,
  },
  {
    id: "paint_advanced",
    title: "Peinture (avancé)",
    description: "Supports, rendement, couches et variantes (à venir).",
    category: "Finition",
    plan: "PREMIUM",
    href: "/dashboard/calculators/painting",
    featureKey: "painting",
    status: "AVAILABLE",
    iconName: "🎨",
    isAvailable: true,
  },
  {
    id: "plaster",
    title: "Enduit",
    description: "Quantités d’enduit, ciment/sable et surfaces (à venir).",
    category: "Finition",
    plan: "PREMIUM",
    href: "/dashboard/calculators/plaster",
    featureKey: "plaster",
    status: "AVAILABLE",
    iconName: "🧱",
    isAvailable: true,
  },
  {
    id: "earthwork",
    title: "Terrassement",
    description: "Volumes de déblais/remblais (à venir).",
    category: "Chantier",
    plan: "PREMIUM",
    href: "/dashboard/calculators/earthwork",
    featureKey: "earthwork",
    status: "AVAILABLE",
    iconName: "🚜",
    isAvailable: true,
  },
  {
    id: "roofing",
    title: "Toiture",
    description: "Surfaces, pentes et quantités selon couverture (à venir).",
    category: "Chantier",
    plan: "PREMIUM",
    href: "/dashboard/calculators/roofing",
    featureKey: "roofing",
    status: "AVAILABLE",
    iconName: "🏠",
    isAvailable: true,
  },
  {
    id: "formwork",
    title: "Coffrage",
    description: "Surfaces de coffrage estimatives (à venir).",
    category: "Béton",
    plan: "PREMIUM",
    href: "/dashboard/calculators/formwork",
    featureKey: "formwork",
    status: "AVAILABLE",
    iconName: "🪵",
    isAvailable: true,
  },
  {
    id: "stair_landing",
    title: "Escalier avec palier",
    description: "Dimensions et quantités (MVP à venir).",
    category: "Béton",
    plan: "PREMIUM",
    href: "/dashboard/calculators/stairs/landing",
    featureKey: "stair_landing",
    status: "AVAILABLE",
    iconName: "🪜",
    isAvailable: true,
  },

  {
    id: "stair_quarter_turn",
    title: "Escalier quart tournant",
    description: "Pré-dimensionnement et quantités (à venir).",
    category: "Béton",
    plan: "ENTERPRISE",
    href: "/dashboard/calculators/stairs/quarter-turn",
    featureKey: "stair_quarter_turn",
    status: "AVAILABLE",
    iconName: "🪜",
    isAvailable: true,
  },
  {
    id: "septic_tank",
    title: "Fosse septique / puisard",
    description: "Pré-dimensionnement et quantités (à venir).",
    category: "Chantier",
    plan: "ENTERPRISE",
    href: "/dashboard/calculators/septic-tank",
    featureKey: "septic_tank",
    status: "AVAILABLE",
    iconName: "🕳️",
    isAvailable: true,
  },
  {
    id: "fence",
    title: "Clôture",
    description: "Poteaux, linéaire et fondations (à venir).",
    category: "Chantier",
    plan: "ENTERPRISE",
    href: "/dashboard/calculators/fence",
    featureKey: "fence",
    status: "AVAILABLE",
    iconName: "🧱",
    isAvailable: true,
  },
  {
    id: "advanced_slab",
    title: "Dalle pleine (avancé)",
    description: "Béton, aciers, pertes et variantes (à venir).",
    category: "Béton",
    plan: "ENTERPRISE",
    href: "/dashboard/calculators/slab/advanced",
    featureKey: "advanced_slab",
    status: "AVAILABLE",
    iconName: "🧱",
    isAvailable: true,
  },

  {
    id: "calc_history",
    title: "Historique des calculs",
    description: "MVP: historique global des calculs sauvegardés.",
    category: "Outils Pro",
    plan: "PREMIUM",
    href: "/dashboard/calculations/history",
    featureKey: "calc_history",
    status: "AVAILABLE",
    iconName: "🕘",
    isAvailable: true,
  },
  {
    id: "calc_pdf",
    title: "Export PDF calcul",
    description: "MVP: page imprimable + Enregistrer en PDF.",
    category: "Outils Pro",
    plan: "PREMIUM",
    href: "/dashboard/calculations/print",
    featureKey: "calc_pdf",
    status: "AVAILABLE",
    iconName: "📎",
    isAvailable: true,
  },
  {
    id: "quote_from_calc",
    title: "Créer un devis depuis un calcul",
    description: "MVP: pré-remplir un devis depuis un calcul.",
    category: "Devis",
    plan: "PREMIUM",
    href: "/dashboard/quotes",
    featureKey: "quote_from_calc",
    status: "AVAILABLE",
    iconName: "🧾",
    isAvailable: true,
  },
  {
    id: "quote_templates",
    title: "Modèles rapides de devis",
    description: "MVP: modèles rapides de lignes de devis.",
    category: "Devis",
    plan: "PREMIUM",
    href: "/dashboard/quotes",
    featureKey: "quote_templates",
    status: "AVAILABLE",
    iconName: "⚡",
    isAvailable: true,
  },

  {
    id: "price_library",
    title: "Bibliothèque prix matériaux",
    description: "Prix, unités et variantes par fournisseur (bientôt).",
    category: "Outils Pro",
    plan: "ENTERPRISE",
    href: "/pricing",
    status: "SOON",
    iconName: "📚",
    isAvailable: false,
  },
  {
    id: "project_profitability",
    title: "Rentabilité chantier",
    description: "Marge, coûts et rentabilité par projet (bientôt).",
    category: "Chantier",
    plan: "ENTERPRISE",
    href: "/pricing",
    status: "SOON",
    iconName: "📈",
    isAvailable: false,
  },
  {
    id: "reports_pdf",
    title: "Rapports chantier PDF",
    description: "Exports PDF avancés pour rapports (bientôt).",
    category: "Chantier",
    plan: "ENTERPRISE",
    href: "/pricing",
    featureKey: "report_pdf",
    status: "SOON",
    iconName: "📄",
    isAvailable: false,
  },
  {
    id: "expenses_validation",
    title: "Validation dépenses",
    description: "Workflow de validation et contrôle (bientôt).",
    category: "Chantier",
    plan: "ENTERPRISE",
    href: "/pricing",
    status: "SOON",
    iconName: "✅",
    isAvailable: false,
  },
  {
    id: "team_tracking",
    title: "Suivi équipe",
    description: "Affectations, présence et suivi (bientôt).",
    category: "Chantier",
    plan: "ENTERPRISE",
    href: "/pricing",
    featureKey: "team_management",
    status: "SOON",
    iconName: "👷",
    isAvailable: false,
  },
  {
    id: "advanced_exports",
    title: "Exports avancés (Excel/PDF)",
    description: "Exports détaillés et multi-formats (bientôt).",
    category: "Outils Pro",
    plan: "ENTERPRISE",
    href: "/pricing",
    status: "SOON",
    iconName: "📤",
    isAvailable: false,
  },
];
